// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsChimeApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashChimeApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsChimeApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsChimeApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsChimeApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsChimeApi(lhsKey, rhsKey) {
          if deepEqualsChimeApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsChimeApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashChimeApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashChimeApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashChimeApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashChimeApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashChimeApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashChimeApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Generated class from Pigeon that represents data sent in messages.
struct JoinInfoMsg: Hashable {
  var meetingId: String? = nil
  var externalMeetingId: String? = nil
  var mediaRegion: String? = nil
  var audioHostUrl: String? = nil
  var audioFallbackUrl: String? = nil
  var signalingUrl: String? = nil
  var turnControlUrl: String? = nil
  var externalUserId: String? = nil
  var attendeeId: String? = nil
  var joinToken: String? = nil
  /// iOS only: the App Group ID shared between the main app and the
  /// ScreenShareExt broadcast extension (e.g. "group.com.example.app.screenshare").
  /// Required on iOS for screen share to work. Ignored on Android.
  var appGroupId: String? = nil
  /// iOS only: the full bundle identifier of the broadcast upload extension
  /// target (e.g. "com.example.app.ScreenShareExt"). Overrides the default
  /// discovery order, which is: this field, then the `ChimeScreenShareExtension`
  /// Info.plist key in the main app, then the fallback `<mainBundleId>.ScreenShareExt`.
  /// Ignored on Android.
  var screenShareExtensionId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> JoinInfoMsg? {
    let meetingId: String? = nilOrValue(pigeonVar_list[0])
    let externalMeetingId: String? = nilOrValue(pigeonVar_list[1])
    let mediaRegion: String? = nilOrValue(pigeonVar_list[2])
    let audioHostUrl: String? = nilOrValue(pigeonVar_list[3])
    let audioFallbackUrl: String? = nilOrValue(pigeonVar_list[4])
    let signalingUrl: String? = nilOrValue(pigeonVar_list[5])
    let turnControlUrl: String? = nilOrValue(pigeonVar_list[6])
    let externalUserId: String? = nilOrValue(pigeonVar_list[7])
    let attendeeId: String? = nilOrValue(pigeonVar_list[8])
    let joinToken: String? = nilOrValue(pigeonVar_list[9])
    let appGroupId: String? = nilOrValue(pigeonVar_list[10])
    let screenShareExtensionId: String? = nilOrValue(pigeonVar_list[11])

    return JoinInfoMsg(
      meetingId: meetingId,
      externalMeetingId: externalMeetingId,
      mediaRegion: mediaRegion,
      audioHostUrl: audioHostUrl,
      audioFallbackUrl: audioFallbackUrl,
      signalingUrl: signalingUrl,
      turnControlUrl: turnControlUrl,
      externalUserId: externalUserId,
      attendeeId: attendeeId,
      joinToken: joinToken,
      appGroupId: appGroupId,
      screenShareExtensionId: screenShareExtensionId
    )
  }
  func toList() -> [Any?] {
    return [
      meetingId,
      externalMeetingId,
      mediaRegion,
      audioHostUrl,
      audioFallbackUrl,
      signalingUrl,
      turnControlUrl,
      externalUserId,
      attendeeId,
      joinToken,
      appGroupId,
      screenShareExtensionId,
    ]
  }
  static func == (lhs: JoinInfoMsg, rhs: JoinInfoMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsChimeApi(lhs.meetingId, rhs.meetingId) && deepEqualsChimeApi(lhs.externalMeetingId, rhs.externalMeetingId) && deepEqualsChimeApi(lhs.mediaRegion, rhs.mediaRegion) && deepEqualsChimeApi(lhs.audioHostUrl, rhs.audioHostUrl) && deepEqualsChimeApi(lhs.audioFallbackUrl, rhs.audioFallbackUrl) && deepEqualsChimeApi(lhs.signalingUrl, rhs.signalingUrl) && deepEqualsChimeApi(lhs.turnControlUrl, rhs.turnControlUrl) && deepEqualsChimeApi(lhs.externalUserId, rhs.externalUserId) && deepEqualsChimeApi(lhs.attendeeId, rhs.attendeeId) && deepEqualsChimeApi(lhs.joinToken, rhs.joinToken) && deepEqualsChimeApi(lhs.appGroupId, rhs.appGroupId) && deepEqualsChimeApi(lhs.screenShareExtensionId, rhs.screenShareExtensionId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("JoinInfoMsg")
    deepHashChimeApi(value: meetingId, hasher: &hasher)
    deepHashChimeApi(value: externalMeetingId, hasher: &hasher)
    deepHashChimeApi(value: mediaRegion, hasher: &hasher)
    deepHashChimeApi(value: audioHostUrl, hasher: &hasher)
    deepHashChimeApi(value: audioFallbackUrl, hasher: &hasher)
    deepHashChimeApi(value: signalingUrl, hasher: &hasher)
    deepHashChimeApi(value: turnControlUrl, hasher: &hasher)
    deepHashChimeApi(value: externalUserId, hasher: &hasher)
    deepHashChimeApi(value: attendeeId, hasher: &hasher)
    deepHashChimeApi(value: joinToken, hasher: &hasher)
    deepHashChimeApi(value: appGroupId, hasher: &hasher)
    deepHashChimeApi(value: screenShareExtensionId, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AttendeeMsg: Hashable {
  var attendeeId: String? = nil
  var externalUserId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AttendeeMsg? {
    let attendeeId: String? = nilOrValue(pigeonVar_list[0])
    let externalUserId: String? = nilOrValue(pigeonVar_list[1])

    return AttendeeMsg(
      attendeeId: attendeeId,
      externalUserId: externalUserId
    )
  }
  func toList() -> [Any?] {
    return [
      attendeeId,
      externalUserId,
    ]
  }
  static func == (lhs: AttendeeMsg, rhs: AttendeeMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsChimeApi(lhs.attendeeId, rhs.attendeeId) && deepEqualsChimeApi(lhs.externalUserId, rhs.externalUserId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AttendeeMsg")
    deepHashChimeApi(value: attendeeId, hasher: &hasher)
    deepHashChimeApi(value: externalUserId, hasher: &hasher)
  }
}

/// Carries a single attendee's volume level update.
/// [volume]: 0=muted, 1=notSpeaking, 2=low, 3=medium, 4=high
///
/// Generated class from Pigeon that represents data sent in messages.
struct AttendeeVolumeMsg: Hashable {
  var attendeeId: String? = nil
  var externalUserId: String? = nil
  var volume: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AttendeeVolumeMsg? {
    let attendeeId: String? = nilOrValue(pigeonVar_list[0])
    let externalUserId: String? = nilOrValue(pigeonVar_list[1])
    let volume: Int64? = nilOrValue(pigeonVar_list[2])

    return AttendeeVolumeMsg(
      attendeeId: attendeeId,
      externalUserId: externalUserId,
      volume: volume
    )
  }
  func toList() -> [Any?] {
    return [
      attendeeId,
      externalUserId,
      volume,
    ]
  }
  static func == (lhs: AttendeeVolumeMsg, rhs: AttendeeVolumeMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsChimeApi(lhs.attendeeId, rhs.attendeeId) && deepEqualsChimeApi(lhs.externalUserId, rhs.externalUserId) && deepEqualsChimeApi(lhs.volume, rhs.volume)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AttendeeVolumeMsg")
    deepHashChimeApi(value: attendeeId, hasher: &hasher)
    deepHashChimeApi(value: externalUserId, hasher: &hasher)
    deepHashChimeApi(value: volume, hasher: &hasher)
  }
}

/// Carries a single attendee's signal strength update.
/// [signalStrength]: 0=none, 1=low, 2=high
///
/// Generated class from Pigeon that represents data sent in messages.
struct AttendeeSignalMsg: Hashable {
  var attendeeId: String? = nil
  var externalUserId: String? = nil
  var signalStrength: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AttendeeSignalMsg? {
    let attendeeId: String? = nilOrValue(pigeonVar_list[0])
    let externalUserId: String? = nilOrValue(pigeonVar_list[1])
    let signalStrength: Int64? = nilOrValue(pigeonVar_list[2])

    return AttendeeSignalMsg(
      attendeeId: attendeeId,
      externalUserId: externalUserId,
      signalStrength: signalStrength
    )
  }
  func toList() -> [Any?] {
    return [
      attendeeId,
      externalUserId,
      signalStrength,
    ]
  }
  static func == (lhs: AttendeeSignalMsg, rhs: AttendeeSignalMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsChimeApi(lhs.attendeeId, rhs.attendeeId) && deepEqualsChimeApi(lhs.externalUserId, rhs.externalUserId) && deepEqualsChimeApi(lhs.signalStrength, rhs.signalStrength)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AttendeeSignalMsg")
    deepHashChimeApi(value: attendeeId, hasher: &hasher)
    deepHashChimeApi(value: externalUserId, hasher: &hasher)
    deepHashChimeApi(value: signalStrength, hasher: &hasher)
  }
}

/// A real-time data message sent between attendees.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DataMessageMsg: Hashable {
  /// The topic/channel this message was sent on.
  var topic: String? = nil
  /// The UTF-8 string payload.
  var data: String? = nil
  var senderAttendeeId: String? = nil
  var senderExternalUserId: String? = nil
  /// Server timestamp in milliseconds since epoch.
  var timestampMs: Int64? = nil
  /// True if the message was throttled by the server.
  var throttled: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DataMessageMsg? {
    let topic: String? = nilOrValue(pigeonVar_list[0])
    let data: String? = nilOrValue(pigeonVar_list[1])
    let senderAttendeeId: String? = nilOrValue(pigeonVar_list[2])
    let senderExternalUserId: String? = nilOrValue(pigeonVar_list[3])
    let timestampMs: Int64? = nilOrValue(pigeonVar_list[4])
    let throttled: Bool? = nilOrValue(pigeonVar_list[5])

    return DataMessageMsg(
      topic: topic,
      data: data,
      senderAttendeeId: senderAttendeeId,
      senderExternalUserId: senderExternalUserId,
      timestampMs: timestampMs,
      throttled: throttled
    )
  }
  func toList() -> [Any?] {
    return [
      topic,
      data,
      senderAttendeeId,
      senderExternalUserId,
      timestampMs,
      throttled,
    ]
  }
  static func == (lhs: DataMessageMsg, rhs: DataMessageMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsChimeApi(lhs.topic, rhs.topic) && deepEqualsChimeApi(lhs.data, rhs.data) && deepEqualsChimeApi(lhs.senderAttendeeId, rhs.senderAttendeeId) && deepEqualsChimeApi(lhs.senderExternalUserId, rhs.senderExternalUserId) && deepEqualsChimeApi(lhs.timestampMs, rhs.timestampMs) && deepEqualsChimeApi(lhs.throttled, rhs.throttled)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DataMessageMsg")
    deepHashChimeApi(value: topic, hasher: &hasher)
    deepHashChimeApi(value: data, hasher: &hasher)
    deepHashChimeApi(value: senderAttendeeId, hasher: &hasher)
    deepHashChimeApi(value: senderExternalUserId, hasher: &hasher)
    deepHashChimeApi(value: timestampMs, hasher: &hasher)
    deepHashChimeApi(value: throttled, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VideoTileMsg: Hashable {
  var tileId: Int64? = nil
  var attendeeId: String? = nil
  var videoStreamContentHeight: Int64? = nil
  var videoStreamContentWidth: Int64? = nil
  var isLocalTile: Bool? = nil
  var isDisplayOn: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoTileMsg? {
    let tileId: Int64? = nilOrValue(pigeonVar_list[0])
    let attendeeId: String? = nilOrValue(pigeonVar_list[1])
    let videoStreamContentHeight: Int64? = nilOrValue(pigeonVar_list[2])
    let videoStreamContentWidth: Int64? = nilOrValue(pigeonVar_list[3])
    let isLocalTile: Bool? = nilOrValue(pigeonVar_list[4])
    let isDisplayOn: Bool? = nilOrValue(pigeonVar_list[5])

    return VideoTileMsg(
      tileId: tileId,
      attendeeId: attendeeId,
      videoStreamContentHeight: videoStreamContentHeight,
      videoStreamContentWidth: videoStreamContentWidth,
      isLocalTile: isLocalTile,
      isDisplayOn: isDisplayOn
    )
  }
  func toList() -> [Any?] {
    return [
      tileId,
      attendeeId,
      videoStreamContentHeight,
      videoStreamContentWidth,
      isLocalTile,
      isDisplayOn,
    ]
  }
  static func == (lhs: VideoTileMsg, rhs: VideoTileMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsChimeApi(lhs.tileId, rhs.tileId) && deepEqualsChimeApi(lhs.attendeeId, rhs.attendeeId) && deepEqualsChimeApi(lhs.videoStreamContentHeight, rhs.videoStreamContentHeight) && deepEqualsChimeApi(lhs.videoStreamContentWidth, rhs.videoStreamContentWidth) && deepEqualsChimeApi(lhs.isLocalTile, rhs.isLocalTile) && deepEqualsChimeApi(lhs.isDisplayOn, rhs.isDisplayOn)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VideoTileMsg")
    deepHashChimeApi(value: tileId, hasher: &hasher)
    deepHashChimeApi(value: attendeeId, hasher: &hasher)
    deepHashChimeApi(value: videoStreamContentHeight, hasher: &hasher)
    deepHashChimeApi(value: videoStreamContentWidth, hasher: &hasher)
    deepHashChimeApi(value: isLocalTile, hasher: &hasher)
    deepHashChimeApi(value: isDisplayOn, hasher: &hasher)
  }
}

/// Identifies a remote attendee's video source.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RemoteVideoSourceMsg: Hashable {
  var attendeeId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RemoteVideoSourceMsg? {
    let attendeeId: String? = nilOrValue(pigeonVar_list[0])

    return RemoteVideoSourceMsg(
      attendeeId: attendeeId
    )
  }
  func toList() -> [Any?] {
    return [
      attendeeId
    ]
  }
  static func == (lhs: RemoteVideoSourceMsg, rhs: RemoteVideoSourceMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsChimeApi(lhs.attendeeId, rhs.attendeeId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RemoteVideoSourceMsg")
    deepHashChimeApi(value: attendeeId, hasher: &hasher)
  }
}

private class ChimeApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return JoinInfoMsg.fromList(self.readValue() as! [Any?])
    case 130:
      return AttendeeMsg.fromList(self.readValue() as! [Any?])
    case 131:
      return AttendeeVolumeMsg.fromList(self.readValue() as! [Any?])
    case 132:
      return AttendeeSignalMsg.fromList(self.readValue() as! [Any?])
    case 133:
      return DataMessageMsg.fromList(self.readValue() as! [Any?])
    case 134:
      return VideoTileMsg.fromList(self.readValue() as! [Any?])
    case 135:
      return RemoteVideoSourceMsg.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ChimeApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? JoinInfoMsg {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? AttendeeMsg {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? AttendeeVolumeMsg {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? AttendeeSignalMsg {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? DataMessageMsg {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? VideoTileMsg {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? RemoteVideoSourceMsg {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ChimeApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ChimeApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ChimeApiPigeonCodecWriter(data: data)
  }
}

class ChimeApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ChimeApiPigeonCodec(readerWriter: ChimeApiPigeonCodecReaderWriter())
}


/// Defines operations called from Dart to Native.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ChimeHostApi {
  func manageAudioPermissions(completion: @escaping (Result<Bool, Error>) -> Void)
  func manageVideoPermissions(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Returns true if audio (microphone) permissions are already granted
  /// without showing a dialog. Use before [manageAudioPermissions] to check
  /// whether a rationale UI is needed.
  func hasAudioPermissions() throws -> Bool
  /// Returns true if video (camera) permissions are already granted
  /// without showing a dialog. Use before [manageVideoPermissions] to check
  /// whether a rationale UI is needed.
  func hasVideoPermissions() throws -> Bool
  func joinMeeting(joinInfo: JoinInfoMsg) throws
  func stopMeeting() throws
  func mute() throws -> Bool
  func unmute() throws -> Bool
  func startLocalVideo() throws
  func stopLocalVideo() throws
  func startScreenShare() throws
  func stopScreenShare() throws
  /// Sends a real-time data message to all attendees on [topic].
  /// [lifetimeMs]: how long the message is retained for late joiners (0–300000).
  func sendDataMessage(topic: String, data: String, lifetimeMs: Int64) throws
  /// Switches between front and back camera.
  func switchCamera() throws
  /// Returns the currently active camera facing: "front", "back", or null if unavailable.
  func activeCamera() throws -> String?
  /// Sets the maximum encode bitrate (kbps) for the local video stream.
  /// Pass 0 to use the SDK default. Takes effect immediately if local video is active.
  func setLocalVideoMaxBitrate(maxBitrateKbps: Int64) throws
  /// Subscribes to the given video sources and unsubscribes from the removed ones.
  func updateVideoSourceSubscriptions(toAdd: [RemoteVideoSourceMsg?], toRemove: [RemoteVideoSourceMsg?]) throws
  func initialAudioSelection() throws -> String?
  func listAudioDevices() throws -> [String?]
  func updateAudioDevice(deviceName: String) throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ChimeHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ChimeApiPigeonCodec.shared }
  /// Sets up an instance of `ChimeHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ChimeHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let manageAudioPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.manageAudioPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      manageAudioPermissionsChannel.setMessageHandler { _, reply in
        api.manageAudioPermissions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      manageAudioPermissionsChannel.setMessageHandler(nil)
    }
    let manageVideoPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.manageVideoPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      manageVideoPermissionsChannel.setMessageHandler { _, reply in
        api.manageVideoPermissions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      manageVideoPermissionsChannel.setMessageHandler(nil)
    }
    /// Returns true if audio (microphone) permissions are already granted
    /// without showing a dialog. Use before [manageAudioPermissions] to check
    /// whether a rationale UI is needed.
    let hasAudioPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.hasAudioPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasAudioPermissionsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.hasAudioPermissions()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hasAudioPermissionsChannel.setMessageHandler(nil)
    }
    /// Returns true if video (camera) permissions are already granted
    /// without showing a dialog. Use before [manageVideoPermissions] to check
    /// whether a rationale UI is needed.
    let hasVideoPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.hasVideoPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasVideoPermissionsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.hasVideoPermissions()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hasVideoPermissionsChannel.setMessageHandler(nil)
    }
    let joinMeetingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.joinMeeting\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      joinMeetingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let joinInfoArg = args[0] as! JoinInfoMsg
        do {
          try api.joinMeeting(joinInfo: joinInfoArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      joinMeetingChannel.setMessageHandler(nil)
    }
    let stopMeetingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.stopMeeting\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopMeetingChannel.setMessageHandler { _, reply in
        do {
          try api.stopMeeting()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopMeetingChannel.setMessageHandler(nil)
    }
    let muteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.mute\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      muteChannel.setMessageHandler { _, reply in
        do {
          let result = try api.mute()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      muteChannel.setMessageHandler(nil)
    }
    let unmuteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.unmute\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unmuteChannel.setMessageHandler { _, reply in
        do {
          let result = try api.unmute()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      unmuteChannel.setMessageHandler(nil)
    }
    let startLocalVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.startLocalVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startLocalVideoChannel.setMessageHandler { _, reply in
        do {
          try api.startLocalVideo()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startLocalVideoChannel.setMessageHandler(nil)
    }
    let stopLocalVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.stopLocalVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopLocalVideoChannel.setMessageHandler { _, reply in
        do {
          try api.stopLocalVideo()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopLocalVideoChannel.setMessageHandler(nil)
    }
    let startScreenShareChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.startScreenShare\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startScreenShareChannel.setMessageHandler { _, reply in
        do {
          try api.startScreenShare()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startScreenShareChannel.setMessageHandler(nil)
    }
    let stopScreenShareChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.stopScreenShare\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopScreenShareChannel.setMessageHandler { _, reply in
        do {
          try api.stopScreenShare()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopScreenShareChannel.setMessageHandler(nil)
    }
    /// Sends a real-time data message to all attendees on [topic].
    /// [lifetimeMs]: how long the message is retained for late joiners (0–300000).
    let sendDataMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.sendDataMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendDataMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let topicArg = args[0] as! String
        let dataArg = args[1] as! String
        let lifetimeMsArg = args[2] as! Int64
        do {
          try api.sendDataMessage(topic: topicArg, data: dataArg, lifetimeMs: lifetimeMsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendDataMessageChannel.setMessageHandler(nil)
    }
    /// Switches between front and back camera.
    let switchCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.switchCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      switchCameraChannel.setMessageHandler { _, reply in
        do {
          try api.switchCamera()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      switchCameraChannel.setMessageHandler(nil)
    }
    /// Returns the currently active camera facing: "front", "back", or null if unavailable.
    let activeCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.activeCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      activeCameraChannel.setMessageHandler { _, reply in
        do {
          let result = try api.activeCamera()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      activeCameraChannel.setMessageHandler(nil)
    }
    /// Sets the maximum encode bitrate (kbps) for the local video stream.
    /// Pass 0 to use the SDK default. Takes effect immediately if local video is active.
    let setLocalVideoMaxBitrateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.setLocalVideoMaxBitrate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLocalVideoMaxBitrateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let maxBitrateKbpsArg = args[0] as! Int64
        do {
          try api.setLocalVideoMaxBitrate(maxBitrateKbps: maxBitrateKbpsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLocalVideoMaxBitrateChannel.setMessageHandler(nil)
    }
    /// Subscribes to the given video sources and unsubscribes from the removed ones.
    let updateVideoSourceSubscriptionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.updateVideoSourceSubscriptions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateVideoSourceSubscriptionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let toAddArg = args[0] as! [RemoteVideoSourceMsg?]
        let toRemoveArg = args[1] as! [RemoteVideoSourceMsg?]
        do {
          try api.updateVideoSourceSubscriptions(toAdd: toAddArg, toRemove: toRemoveArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateVideoSourceSubscriptionsChannel.setMessageHandler(nil)
    }
    let initialAudioSelectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.initialAudioSelection\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initialAudioSelectionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.initialAudioSelection()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initialAudioSelectionChannel.setMessageHandler(nil)
    }
    let listAudioDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.listAudioDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listAudioDevicesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.listAudioDevices()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      listAudioDevicesChannel.setMessageHandler(nil)
    }
    let updateAudioDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.updateAudioDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateAudioDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceNameArg = args[0] as! String
        do {
          let result = try api.updateAudioDevice(deviceName: deviceNameArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateAudioDeviceChannel.setMessageHandler(nil)
    }
  }
}
/// Defines operations called from Native to Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ChimeFlutterApiProtocol {
  func onAttendeeJoined(attendee attendeeArg: AttendeeMsg, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAttendeeLeft(attendee attendeeArg: AttendeeMsg, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAttendeeDropped(attendee attendeeArg: AttendeeMsg, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAttendeeMuted(attendee attendeeArg: AttendeeMsg, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAttendeeUnmuted(attendee attendeeArg: AttendeeMsg, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onVideoTileAdded(tile tileArg: VideoTileMsg, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onVideoTileRemoved(tile tileArg: VideoTileMsg, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAudioSessionStarted(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAudioSessionStopped(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAudioSessionStartConnecting(reconnecting reconnectingArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAudioSessionDropped(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAudioSessionCancelledReconnect(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// [isPoor]: true when connection became poor, false when it recovered.
  func onConnectionQualityChanged(isPoor isPoorArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onActiveSpeakersChanged(attendeeIds attendeeIdsArg: [String?], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onVideoTilePaused(tile tileArg: VideoTileMsg, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onVideoTileResumed(tile tileArg: VideoTileMsg, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// [state]: 0=started, 1=stopped
  func onContentShareStateChanged(state stateArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAttendeesVolumeChanged(updates updatesArg: [AttendeeVolumeMsg], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAttendeesSignalChanged(updates updatesArg: [AttendeeSignalMsg], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDataMessageReceived(message messageArg: DataMessageMsg, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onRemoteVideoSourcesAvailable(sources sourcesArg: [RemoteVideoSourceMsg?], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onRemoteVideoSourcesUnavailable(sources sourcesArg: [RemoteVideoSourceMsg?], completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Periodic metrics: map of metric name → numeric value.
  func onMeetingMetricsReceived(metrics metricsArg: [String?: Any?], completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Structured analytics event from the SDK (e.g. meetingStartSucceeded, meetingFailed).
  func onMeetingEventReceived(name nameArg: String, attributes attributesArg: [String?: Any?], completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ChimeFlutterApi: ChimeFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: ChimeApiPigeonCodec {
    return ChimeApiPigeonCodec.shared
  }
  func onAttendeeJoined(attendee attendeeArg: AttendeeMsg, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeeJoined\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([attendeeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAttendeeLeft(attendee attendeeArg: AttendeeMsg, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeeLeft\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([attendeeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAttendeeDropped(attendee attendeeArg: AttendeeMsg, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeeDropped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([attendeeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAttendeeMuted(attendee attendeeArg: AttendeeMsg, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeeMuted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([attendeeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAttendeeUnmuted(attendee attendeeArg: AttendeeMsg, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeeUnmuted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([attendeeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onVideoTileAdded(tile tileArg: VideoTileMsg, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onVideoTileAdded\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([tileArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onVideoTileRemoved(tile tileArg: VideoTileMsg, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onVideoTileRemoved\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([tileArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAudioSessionStarted(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAudioSessionStarted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAudioSessionStopped(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAudioSessionStopped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAudioSessionStartConnecting(reconnecting reconnectingArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAudioSessionStartConnecting\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([reconnectingArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAudioSessionDropped(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAudioSessionDropped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAudioSessionCancelledReconnect(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAudioSessionCancelledReconnect\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// [isPoor]: true when connection became poor, false when it recovered.
  func onConnectionQualityChanged(isPoor isPoorArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onConnectionQualityChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([isPoorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onActiveSpeakersChanged(attendeeIds attendeeIdsArg: [String?], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onActiveSpeakersChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([attendeeIdsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onVideoTilePaused(tile tileArg: VideoTileMsg, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onVideoTilePaused\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([tileArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onVideoTileResumed(tile tileArg: VideoTileMsg, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onVideoTileResumed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([tileArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// [state]: 0=started, 1=stopped
  func onContentShareStateChanged(state stateArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onContentShareStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAttendeesVolumeChanged(updates updatesArg: [AttendeeVolumeMsg], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeesVolumeChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([updatesArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAttendeesSignalChanged(updates updatesArg: [AttendeeSignalMsg], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeesSignalChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([updatesArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onDataMessageReceived(message messageArg: DataMessageMsg, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onDataMessageReceived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onRemoteVideoSourcesAvailable(sources sourcesArg: [RemoteVideoSourceMsg?], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onRemoteVideoSourcesAvailable\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sourcesArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onRemoteVideoSourcesUnavailable(sources sourcesArg: [RemoteVideoSourceMsg?], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onRemoteVideoSourcesUnavailable\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sourcesArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Periodic metrics: map of metric name → numeric value.
  func onMeetingMetricsReceived(metrics metricsArg: [String?: Any?], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onMeetingMetricsReceived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([metricsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Structured analytics event from the SDK (e.g. meetingStartSucceeded, meetingFailed).
  func onMeetingEventReceived(name nameArg: String, attributes attributesArg: [String?: Any?], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onMeetingEventReceived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([nameArg, attributesArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
