// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class JoinInfoMsg {
  JoinInfoMsg({
    this.meetingId,
    this.externalMeetingId,
    this.mediaRegion,
    this.audioHostUrl,
    this.audioFallbackUrl,
    this.signalingUrl,
    this.turnControlUrl,
    this.externalUserId,
    this.attendeeId,
    this.joinToken,
    this.appGroupId,
    this.screenShareExtensionId,
  });

  String? meetingId;

  String? externalMeetingId;

  String? mediaRegion;

  String? audioHostUrl;

  String? audioFallbackUrl;

  String? signalingUrl;

  String? turnControlUrl;

  String? externalUserId;

  String? attendeeId;

  String? joinToken;

  /// iOS only: the App Group ID shared between the main app and the
  /// ScreenShareExt broadcast extension (e.g. "group.com.example.app.screenshare").
  /// Required on iOS for screen share to work. Ignored on Android.
  String? appGroupId;

  /// iOS only: the full bundle identifier of the broadcast upload extension
  /// target (e.g. "com.example.app.ScreenShareExt"). Overrides the default
  /// discovery order, which is: this field, then the `ChimeScreenShareExtension`
  /// Info.plist key in the main app, then the fallback `<mainBundleId>.ScreenShareExt`.
  /// Ignored on Android.
  String? screenShareExtensionId;

  List<Object?> _toList() {
    return <Object?>[
      meetingId,
      externalMeetingId,
      mediaRegion,
      audioHostUrl,
      audioFallbackUrl,
      signalingUrl,
      turnControlUrl,
      externalUserId,
      attendeeId,
      joinToken,
      appGroupId,
      screenShareExtensionId,
    ];
  }

  Object encode() {
    return _toList();  }

  static JoinInfoMsg decode(Object result) {
    result as List<Object?>;
    return JoinInfoMsg(
      meetingId: result[0] as String?,
      externalMeetingId: result[1] as String?,
      mediaRegion: result[2] as String?,
      audioHostUrl: result[3] as String?,
      audioFallbackUrl: result[4] as String?,
      signalingUrl: result[5] as String?,
      turnControlUrl: result[6] as String?,
      externalUserId: result[7] as String?,
      attendeeId: result[8] as String?,
      joinToken: result[9] as String?,
      appGroupId: result[10] as String?,
      screenShareExtensionId: result[11] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! JoinInfoMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(meetingId, other.meetingId) && _deepEquals(externalMeetingId, other.externalMeetingId) && _deepEquals(mediaRegion, other.mediaRegion) && _deepEquals(audioHostUrl, other.audioHostUrl) && _deepEquals(audioFallbackUrl, other.audioFallbackUrl) && _deepEquals(signalingUrl, other.signalingUrl) && _deepEquals(turnControlUrl, other.turnControlUrl) && _deepEquals(externalUserId, other.externalUserId) && _deepEquals(attendeeId, other.attendeeId) && _deepEquals(joinToken, other.joinToken) && _deepEquals(appGroupId, other.appGroupId) && _deepEquals(screenShareExtensionId, other.screenShareExtensionId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class AttendeeMsg {
  AttendeeMsg({
    this.attendeeId,
    this.externalUserId,
  });

  String? attendeeId;

  String? externalUserId;

  List<Object?> _toList() {
    return <Object?>[
      attendeeId,
      externalUserId,
    ];
  }

  Object encode() {
    return _toList();  }

  static AttendeeMsg decode(Object result) {
    result as List<Object?>;
    return AttendeeMsg(
      attendeeId: result[0] as String?,
      externalUserId: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AttendeeMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(attendeeId, other.attendeeId) && _deepEquals(externalUserId, other.externalUserId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Carries a single attendee's volume level update.
/// [volume]: 0=muted, 1=notSpeaking, 2=low, 3=medium, 4=high
class AttendeeVolumeMsg {
  AttendeeVolumeMsg({
    this.attendeeId,
    this.externalUserId,
    this.volume,
  });

  String? attendeeId;

  String? externalUserId;

  int? volume;

  List<Object?> _toList() {
    return <Object?>[
      attendeeId,
      externalUserId,
      volume,
    ];
  }

  Object encode() {
    return _toList();  }

  static AttendeeVolumeMsg decode(Object result) {
    result as List<Object?>;
    return AttendeeVolumeMsg(
      attendeeId: result[0] as String?,
      externalUserId: result[1] as String?,
      volume: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AttendeeVolumeMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(attendeeId, other.attendeeId) && _deepEquals(externalUserId, other.externalUserId) && _deepEquals(volume, other.volume);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Carries a single attendee's signal strength update.
/// [signalStrength]: 0=none, 1=low, 2=high
class AttendeeSignalMsg {
  AttendeeSignalMsg({
    this.attendeeId,
    this.externalUserId,
    this.signalStrength,
  });

  String? attendeeId;

  String? externalUserId;

  int? signalStrength;

  List<Object?> _toList() {
    return <Object?>[
      attendeeId,
      externalUserId,
      signalStrength,
    ];
  }

  Object encode() {
    return _toList();  }

  static AttendeeSignalMsg decode(Object result) {
    result as List<Object?>;
    return AttendeeSignalMsg(
      attendeeId: result[0] as String?,
      externalUserId: result[1] as String?,
      signalStrength: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AttendeeSignalMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(attendeeId, other.attendeeId) && _deepEquals(externalUserId, other.externalUserId) && _deepEquals(signalStrength, other.signalStrength);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A real-time data message sent between attendees.
class DataMessageMsg {
  DataMessageMsg({
    this.topic,
    this.data,
    this.senderAttendeeId,
    this.senderExternalUserId,
    this.timestampMs,
    this.throttled,
  });

  /// The topic/channel this message was sent on.
  String? topic;

  /// The UTF-8 string payload.
  String? data;

  String? senderAttendeeId;

  String? senderExternalUserId;

  /// Server timestamp in milliseconds since epoch.
  int? timestampMs;

  /// True if the message was throttled by the server.
  bool? throttled;

  List<Object?> _toList() {
    return <Object?>[
      topic,
      data,
      senderAttendeeId,
      senderExternalUserId,
      timestampMs,
      throttled,
    ];
  }

  Object encode() {
    return _toList();  }

  static DataMessageMsg decode(Object result) {
    result as List<Object?>;
    return DataMessageMsg(
      topic: result[0] as String?,
      data: result[1] as String?,
      senderAttendeeId: result[2] as String?,
      senderExternalUserId: result[3] as String?,
      timestampMs: result[4] as int?,
      throttled: result[5] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DataMessageMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(topic, other.topic) && _deepEquals(data, other.data) && _deepEquals(senderAttendeeId, other.senderAttendeeId) && _deepEquals(senderExternalUserId, other.senderExternalUserId) && _deepEquals(timestampMs, other.timestampMs) && _deepEquals(throttled, other.throttled);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class VideoTileMsg {
  VideoTileMsg({
    this.tileId,
    this.attendeeId,
    this.videoStreamContentHeight,
    this.videoStreamContentWidth,
    this.isLocalTile,
    this.isDisplayOn,
  });

  int? tileId;

  String? attendeeId;

  int? videoStreamContentHeight;

  int? videoStreamContentWidth;

  bool? isLocalTile;

  bool? isDisplayOn;

  List<Object?> _toList() {
    return <Object?>[
      tileId,
      attendeeId,
      videoStreamContentHeight,
      videoStreamContentWidth,
      isLocalTile,
      isDisplayOn,
    ];
  }

  Object encode() {
    return _toList();  }

  static VideoTileMsg decode(Object result) {
    result as List<Object?>;
    return VideoTileMsg(
      tileId: result[0] as int?,
      attendeeId: result[1] as String?,
      videoStreamContentHeight: result[2] as int?,
      videoStreamContentWidth: result[3] as int?,
      isLocalTile: result[4] as bool?,
      isDisplayOn: result[5] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoTileMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(tileId, other.tileId) && _deepEquals(attendeeId, other.attendeeId) && _deepEquals(videoStreamContentHeight, other.videoStreamContentHeight) && _deepEquals(videoStreamContentWidth, other.videoStreamContentWidth) && _deepEquals(isLocalTile, other.isLocalTile) && _deepEquals(isDisplayOn, other.isDisplayOn);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Identifies a remote attendee's video source.
class RemoteVideoSourceMsg {
  RemoteVideoSourceMsg({
    this.attendeeId,
  });

  String? attendeeId;

  List<Object?> _toList() {
    return <Object?>[
      attendeeId,
    ];
  }

  Object encode() {
    return _toList();  }

  static RemoteVideoSourceMsg decode(Object result) {
    result as List<Object?>;
    return RemoteVideoSourceMsg(
      attendeeId: result[0] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RemoteVideoSourceMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(attendeeId, other.attendeeId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is JoinInfoMsg) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is AttendeeMsg) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is AttendeeVolumeMsg) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is AttendeeSignalMsg) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is DataMessageMsg) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is VideoTileMsg) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is RemoteVideoSourceMsg) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return JoinInfoMsg.decode(readValue(buffer)!);
      case 130:
        return AttendeeMsg.decode(readValue(buffer)!);
      case 131:
        return AttendeeVolumeMsg.decode(readValue(buffer)!);
      case 132:
        return AttendeeSignalMsg.decode(readValue(buffer)!);
      case 133:
        return DataMessageMsg.decode(readValue(buffer)!);
      case 134:
        return VideoTileMsg.decode(readValue(buffer)!);
      case 135:
        return RemoteVideoSourceMsg.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Defines operations called from Dart to Native.
class ChimeHostApi {
  /// Constructor for [ChimeHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ChimeHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> manageAudioPermissions() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.manageAudioPermissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> manageVideoPermissions() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.manageVideoPermissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Returns true if audio (microphone) permissions are already granted
  /// without showing a dialog. Use before [manageAudioPermissions] to check
  /// whether a rationale UI is needed.
  Future<bool> hasAudioPermissions() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.hasAudioPermissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Returns true if video (camera) permissions are already granted
  /// without showing a dialog. Use before [manageVideoPermissions] to check
  /// whether a rationale UI is needed.
  Future<bool> hasVideoPermissions() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.hasVideoPermissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> joinMeeting(JoinInfoMsg joinInfo) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.joinMeeting$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[joinInfo]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopMeeting() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.stopMeeting$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<bool> mute() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.mute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> unmute() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.unmute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> startLocalVideo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.startLocalVideo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopLocalVideo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.stopLocalVideo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> startScreenShare() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.startScreenShare$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopScreenShare() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.stopScreenShare$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Sends a real-time data message to all attendees on [topic].
  /// [lifetimeMs]: how long the message is retained for late joiners (0–300000).
  Future<void> sendDataMessage(String topic, String data, int lifetimeMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.sendDataMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[topic, data, lifetimeMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Switches between front and back camera.
  Future<void> switchCamera() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.switchCamera$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Returns the currently active camera facing: "front", "back", or null if unavailable.
  Future<String?> activeCamera() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.activeCamera$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  /// Sets the maximum encode bitrate (kbps) for the local video stream.
  /// Pass 0 to use the SDK default. Takes effect immediately if local video is active.
  Future<void> setLocalVideoMaxBitrate(int maxBitrateKbps) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.setLocalVideoMaxBitrate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[maxBitrateKbps]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Subscribes to the given video sources and unsubscribes from the removed ones.
  Future<void> updateVideoSourceSubscriptions(List<RemoteVideoSourceMsg?> toAdd, List<RemoteVideoSourceMsg?> toRemove) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.updateVideoSourceSubscriptions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[toAdd, toRemove]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<String?> initialAudioSelection() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.initialAudioSelection$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  Future<List<String?>> listAudioDevices() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.listAudioDevices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String?>();
  }

  Future<bool> updateAudioDevice(String deviceName) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.updateAudioDevice$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceName]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }
}

/// Defines operations called from Native to Dart.
abstract class ChimeFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onAttendeeJoined(AttendeeMsg attendee);

  void onAttendeeLeft(AttendeeMsg attendee);

  void onAttendeeDropped(AttendeeMsg attendee);

  void onAttendeeMuted(AttendeeMsg attendee);

  void onAttendeeUnmuted(AttendeeMsg attendee);

  void onVideoTileAdded(VideoTileMsg tile);

  void onVideoTileRemoved(VideoTileMsg tile);

  void onAudioSessionStarted();

  void onAudioSessionStopped();

  void onAudioSessionStartConnecting(bool reconnecting);

  void onAudioSessionDropped();

  void onAudioSessionCancelledReconnect();

  /// [isPoor]: true when connection became poor, false when it recovered.
  void onConnectionQualityChanged(bool isPoor);

  void onActiveSpeakersChanged(List<String?> attendeeIds);

  void onVideoTilePaused(VideoTileMsg tile);

  void onVideoTileResumed(VideoTileMsg tile);

  /// [state]: 0=started, 1=stopped
  void onContentShareStateChanged(int state);

  void onAttendeesVolumeChanged(List<AttendeeVolumeMsg> updates);

  void onAttendeesSignalChanged(List<AttendeeSignalMsg> updates);

  void onDataMessageReceived(DataMessageMsg message);

  void onRemoteVideoSourcesAvailable(List<RemoteVideoSourceMsg?> sources);

  void onRemoteVideoSourcesUnavailable(List<RemoteVideoSourceMsg?> sources);

  /// Periodic metrics: map of metric name → numeric value.
  void onMeetingMetricsReceived(Map<String?, Object?> metrics);

  /// Structured analytics event from the SDK (e.g. meetingStartSucceeded, meetingFailed).
  void onMeetingEventReceived(String name, Map<String?, Object?> attributes);

  static void setUp(ChimeFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeeJoined$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AttendeeMsg arg_attendee = args[0]! as AttendeeMsg;
          try {
            api.onAttendeeJoined(arg_attendee);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeeLeft$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AttendeeMsg arg_attendee = args[0]! as AttendeeMsg;
          try {
            api.onAttendeeLeft(arg_attendee);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeeDropped$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AttendeeMsg arg_attendee = args[0]! as AttendeeMsg;
          try {
            api.onAttendeeDropped(arg_attendee);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeeMuted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AttendeeMsg arg_attendee = args[0]! as AttendeeMsg;
          try {
            api.onAttendeeMuted(arg_attendee);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeeUnmuted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AttendeeMsg arg_attendee = args[0]! as AttendeeMsg;
          try {
            api.onAttendeeUnmuted(arg_attendee);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onVideoTileAdded$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final VideoTileMsg arg_tile = args[0]! as VideoTileMsg;
          try {
            api.onVideoTileAdded(arg_tile);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onVideoTileRemoved$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final VideoTileMsg arg_tile = args[0]! as VideoTileMsg;
          try {
            api.onVideoTileRemoved(arg_tile);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAudioSessionStarted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onAudioSessionStarted();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAudioSessionStopped$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onAudioSessionStopped();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAudioSessionStartConnecting$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final bool arg_reconnecting = args[0]! as bool;
          try {
            api.onAudioSessionStartConnecting(arg_reconnecting);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAudioSessionDropped$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onAudioSessionDropped();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAudioSessionCancelledReconnect$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onAudioSessionCancelledReconnect();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onConnectionQualityChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final bool arg_isPoor = args[0]! as bool;
          try {
            api.onConnectionQualityChanged(arg_isPoor);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onActiveSpeakersChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final List<String?> arg_attendeeIds = (args[0]! as List<Object?>).cast<String?>();
          try {
            api.onActiveSpeakersChanged(arg_attendeeIds);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onVideoTilePaused$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final VideoTileMsg arg_tile = args[0]! as VideoTileMsg;
          try {
            api.onVideoTilePaused(arg_tile);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onVideoTileResumed$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final VideoTileMsg arg_tile = args[0]! as VideoTileMsg;
          try {
            api.onVideoTileResumed(arg_tile);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onContentShareStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_state = args[0]! as int;
          try {
            api.onContentShareStateChanged(arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeesVolumeChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final List<AttendeeVolumeMsg> arg_updates = (args[0]! as List<Object?>).cast<AttendeeVolumeMsg>();
          try {
            api.onAttendeesVolumeChanged(arg_updates);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeesSignalChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final List<AttendeeSignalMsg> arg_updates = (args[0]! as List<Object?>).cast<AttendeeSignalMsg>();
          try {
            api.onAttendeesSignalChanged(arg_updates);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onDataMessageReceived$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final DataMessageMsg arg_message = args[0]! as DataMessageMsg;
          try {
            api.onDataMessageReceived(arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onRemoteVideoSourcesAvailable$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final List<RemoteVideoSourceMsg?> arg_sources = (args[0]! as List<Object?>).cast<RemoteVideoSourceMsg?>();
          try {
            api.onRemoteVideoSourcesAvailable(arg_sources);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onRemoteVideoSourcesUnavailable$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final List<RemoteVideoSourceMsg?> arg_sources = (args[0]! as List<Object?>).cast<RemoteVideoSourceMsg?>();
          try {
            api.onRemoteVideoSourcesUnavailable(arg_sources);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onMeetingMetricsReceived$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final Map<String?, Object?> arg_metrics = (args[0]! as Map<Object?, Object?>).cast<String?, Object?>();
          try {
            api.onMeetingMetricsReceived(arg_metrics);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onMeetingEventReceived$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_name = args[0]! as String;
          final Map<String?, Object?> arg_attributes = (args[1]! as Map<Object?, Object?>).cast<String?, Object?>();
          try {
            api.onMeetingEventReceived(arg_name, arg_attributes);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
