// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.retozu.flutter_amazon_chime

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ChimeApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class JoinInfoMsg (
  val meetingId: String? = null,
  val externalMeetingId: String? = null,
  val mediaRegion: String? = null,
  val audioHostUrl: String? = null,
  val audioFallbackUrl: String? = null,
  val signalingUrl: String? = null,
  val turnControlUrl: String? = null,
  val externalUserId: String? = null,
  val attendeeId: String? = null,
  val joinToken: String? = null,
  /**
   * iOS only: the App Group ID shared between the main app and the
   * ScreenShareExt broadcast extension (e.g. "group.com.example.app.screenshare").
   * Required on iOS for screen share to work. Ignored on Android.
   */
  val appGroupId: String? = null,
  /**
   * iOS only: the full bundle identifier of the broadcast upload extension
   * target (e.g. "com.example.app.ScreenShareExt"). Overrides the default
   * discovery order, which is: this field, then the `ChimeScreenShareExtension`
   * Info.plist key in the main app, then the fallback `<mainBundleId>.ScreenShareExt`.
   * Ignored on Android.
   */
  val screenShareExtensionId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): JoinInfoMsg {
      val meetingId = pigeonVar_list[0] as String?
      val externalMeetingId = pigeonVar_list[1] as String?
      val mediaRegion = pigeonVar_list[2] as String?
      val audioHostUrl = pigeonVar_list[3] as String?
      val audioFallbackUrl = pigeonVar_list[4] as String?
      val signalingUrl = pigeonVar_list[5] as String?
      val turnControlUrl = pigeonVar_list[6] as String?
      val externalUserId = pigeonVar_list[7] as String?
      val attendeeId = pigeonVar_list[8] as String?
      val joinToken = pigeonVar_list[9] as String?
      val appGroupId = pigeonVar_list[10] as String?
      val screenShareExtensionId = pigeonVar_list[11] as String?
      return JoinInfoMsg(meetingId, externalMeetingId, mediaRegion, audioHostUrl, audioFallbackUrl, signalingUrl, turnControlUrl, externalUserId, attendeeId, joinToken, appGroupId, screenShareExtensionId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      meetingId,
      externalMeetingId,
      mediaRegion,
      audioHostUrl,
      audioFallbackUrl,
      signalingUrl,
      turnControlUrl,
      externalUserId,
      attendeeId,
      joinToken,
      appGroupId,
      screenShareExtensionId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as JoinInfoMsg
    return ChimeApiPigeonUtils.deepEquals(this.meetingId, other.meetingId) && ChimeApiPigeonUtils.deepEquals(this.externalMeetingId, other.externalMeetingId) && ChimeApiPigeonUtils.deepEquals(this.mediaRegion, other.mediaRegion) && ChimeApiPigeonUtils.deepEquals(this.audioHostUrl, other.audioHostUrl) && ChimeApiPigeonUtils.deepEquals(this.audioFallbackUrl, other.audioFallbackUrl) && ChimeApiPigeonUtils.deepEquals(this.signalingUrl, other.signalingUrl) && ChimeApiPigeonUtils.deepEquals(this.turnControlUrl, other.turnControlUrl) && ChimeApiPigeonUtils.deepEquals(this.externalUserId, other.externalUserId) && ChimeApiPigeonUtils.deepEquals(this.attendeeId, other.attendeeId) && ChimeApiPigeonUtils.deepEquals(this.joinToken, other.joinToken) && ChimeApiPigeonUtils.deepEquals(this.appGroupId, other.appGroupId) && ChimeApiPigeonUtils.deepEquals(this.screenShareExtensionId, other.screenShareExtensionId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.meetingId)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.externalMeetingId)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.mediaRegion)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.audioHostUrl)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.audioFallbackUrl)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.signalingUrl)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.turnControlUrl)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.externalUserId)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.attendeeId)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.joinToken)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.appGroupId)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.screenShareExtensionId)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AttendeeMsg (
  val attendeeId: String? = null,
  val externalUserId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AttendeeMsg {
      val attendeeId = pigeonVar_list[0] as String?
      val externalUserId = pigeonVar_list[1] as String?
      return AttendeeMsg(attendeeId, externalUserId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      attendeeId,
      externalUserId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AttendeeMsg
    return ChimeApiPigeonUtils.deepEquals(this.attendeeId, other.attendeeId) && ChimeApiPigeonUtils.deepEquals(this.externalUserId, other.externalUserId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.attendeeId)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.externalUserId)
    return result
  }
}

/**
 * Carries a single attendee's volume level update.
 * [volume]: 0=muted, 1=notSpeaking, 2=low, 3=medium, 4=high
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AttendeeVolumeMsg (
  val attendeeId: String? = null,
  val externalUserId: String? = null,
  val volume: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AttendeeVolumeMsg {
      val attendeeId = pigeonVar_list[0] as String?
      val externalUserId = pigeonVar_list[1] as String?
      val volume = pigeonVar_list[2] as Long?
      return AttendeeVolumeMsg(attendeeId, externalUserId, volume)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      attendeeId,
      externalUserId,
      volume,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AttendeeVolumeMsg
    return ChimeApiPigeonUtils.deepEquals(this.attendeeId, other.attendeeId) && ChimeApiPigeonUtils.deepEquals(this.externalUserId, other.externalUserId) && ChimeApiPigeonUtils.deepEquals(this.volume, other.volume)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.attendeeId)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.externalUserId)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.volume)
    return result
  }
}

/**
 * Carries a single attendee's signal strength update.
 * [signalStrength]: 0=none, 1=low, 2=high
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AttendeeSignalMsg (
  val attendeeId: String? = null,
  val externalUserId: String? = null,
  val signalStrength: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AttendeeSignalMsg {
      val attendeeId = pigeonVar_list[0] as String?
      val externalUserId = pigeonVar_list[1] as String?
      val signalStrength = pigeonVar_list[2] as Long?
      return AttendeeSignalMsg(attendeeId, externalUserId, signalStrength)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      attendeeId,
      externalUserId,
      signalStrength,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AttendeeSignalMsg
    return ChimeApiPigeonUtils.deepEquals(this.attendeeId, other.attendeeId) && ChimeApiPigeonUtils.deepEquals(this.externalUserId, other.externalUserId) && ChimeApiPigeonUtils.deepEquals(this.signalStrength, other.signalStrength)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.attendeeId)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.externalUserId)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.signalStrength)
    return result
  }
}

/**
 * A real-time data message sent between attendees.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DataMessageMsg (
  /** The topic/channel this message was sent on. */
  val topic: String? = null,
  /** The UTF-8 string payload. */
  val data: String? = null,
  val senderAttendeeId: String? = null,
  val senderExternalUserId: String? = null,
  /** Server timestamp in milliseconds since epoch. */
  val timestampMs: Long? = null,
  /** True if the message was throttled by the server. */
  val throttled: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DataMessageMsg {
      val topic = pigeonVar_list[0] as String?
      val data = pigeonVar_list[1] as String?
      val senderAttendeeId = pigeonVar_list[2] as String?
      val senderExternalUserId = pigeonVar_list[3] as String?
      val timestampMs = pigeonVar_list[4] as Long?
      val throttled = pigeonVar_list[5] as Boolean?
      return DataMessageMsg(topic, data, senderAttendeeId, senderExternalUserId, timestampMs, throttled)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      topic,
      data,
      senderAttendeeId,
      senderExternalUserId,
      timestampMs,
      throttled,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DataMessageMsg
    return ChimeApiPigeonUtils.deepEquals(this.topic, other.topic) && ChimeApiPigeonUtils.deepEquals(this.data, other.data) && ChimeApiPigeonUtils.deepEquals(this.senderAttendeeId, other.senderAttendeeId) && ChimeApiPigeonUtils.deepEquals(this.senderExternalUserId, other.senderExternalUserId) && ChimeApiPigeonUtils.deepEquals(this.timestampMs, other.timestampMs) && ChimeApiPigeonUtils.deepEquals(this.throttled, other.throttled)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.topic)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.data)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.senderAttendeeId)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.senderExternalUserId)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.timestampMs)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.throttled)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoTileMsg (
  val tileId: Long? = null,
  val attendeeId: String? = null,
  val videoStreamContentHeight: Long? = null,
  val videoStreamContentWidth: Long? = null,
  val isLocalTile: Boolean? = null,
  val isDisplayOn: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoTileMsg {
      val tileId = pigeonVar_list[0] as Long?
      val attendeeId = pigeonVar_list[1] as String?
      val videoStreamContentHeight = pigeonVar_list[2] as Long?
      val videoStreamContentWidth = pigeonVar_list[3] as Long?
      val isLocalTile = pigeonVar_list[4] as Boolean?
      val isDisplayOn = pigeonVar_list[5] as Boolean?
      return VideoTileMsg(tileId, attendeeId, videoStreamContentHeight, videoStreamContentWidth, isLocalTile, isDisplayOn)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      tileId,
      attendeeId,
      videoStreamContentHeight,
      videoStreamContentWidth,
      isLocalTile,
      isDisplayOn,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoTileMsg
    return ChimeApiPigeonUtils.deepEquals(this.tileId, other.tileId) && ChimeApiPigeonUtils.deepEquals(this.attendeeId, other.attendeeId) && ChimeApiPigeonUtils.deepEquals(this.videoStreamContentHeight, other.videoStreamContentHeight) && ChimeApiPigeonUtils.deepEquals(this.videoStreamContentWidth, other.videoStreamContentWidth) && ChimeApiPigeonUtils.deepEquals(this.isLocalTile, other.isLocalTile) && ChimeApiPigeonUtils.deepEquals(this.isDisplayOn, other.isDisplayOn)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.tileId)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.attendeeId)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.videoStreamContentHeight)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.videoStreamContentWidth)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.isLocalTile)
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.isDisplayOn)
    return result
  }
}

/**
 * Identifies a remote attendee's video source.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RemoteVideoSourceMsg (
  val attendeeId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RemoteVideoSourceMsg {
      val attendeeId = pigeonVar_list[0] as String?
      return RemoteVideoSourceMsg(attendeeId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      attendeeId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RemoteVideoSourceMsg
    return ChimeApiPigeonUtils.deepEquals(this.attendeeId, other.attendeeId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ChimeApiPigeonUtils.deepHash(this.attendeeId)
    return result
  }
}
private open class ChimeApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          JoinInfoMsg.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AttendeeMsg.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AttendeeVolumeMsg.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AttendeeSignalMsg.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DataMessageMsg.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoTileMsg.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RemoteVideoSourceMsg.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is JoinInfoMsg -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AttendeeMsg -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is AttendeeVolumeMsg -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AttendeeSignalMsg -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is DataMessageMsg -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is VideoTileMsg -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is RemoteVideoSourceMsg -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Defines operations called from Dart to Native.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ChimeHostApi {
  fun manageAudioPermissions(callback: (Result<Boolean>) -> Unit)
  fun manageVideoPermissions(callback: (Result<Boolean>) -> Unit)
  /**
   * Returns true if audio (microphone) permissions are already granted
   * without showing a dialog. Use before [manageAudioPermissions] to check
   * whether a rationale UI is needed.
   */
  fun hasAudioPermissions(): Boolean
  /**
   * Returns true if video (camera) permissions are already granted
   * without showing a dialog. Use before [manageVideoPermissions] to check
   * whether a rationale UI is needed.
   */
  fun hasVideoPermissions(): Boolean
  fun joinMeeting(joinInfo: JoinInfoMsg)
  fun stopMeeting()
  fun mute(): Boolean
  fun unmute(): Boolean
  fun startLocalVideo()
  fun stopLocalVideo()
  fun startScreenShare()
  fun stopScreenShare()
  /**
   * Sends a real-time data message to all attendees on [topic].
   * [lifetimeMs]: how long the message is retained for late joiners (0–300000).
   */
  fun sendDataMessage(topic: String, data: String, lifetimeMs: Long)
  /** Switches between front and back camera. */
  fun switchCamera()
  /** Returns the currently active camera facing: "front", "back", or null if unavailable. */
  fun activeCamera(): String?
  /**
   * Sets the maximum encode bitrate (kbps) for the local video stream.
   * Pass 0 to use the SDK default. Takes effect immediately if local video is active.
   */
  fun setLocalVideoMaxBitrate(maxBitrateKbps: Long)
  /** Subscribes to the given video sources and unsubscribes from the removed ones. */
  fun updateVideoSourceSubscriptions(toAdd: List<RemoteVideoSourceMsg?>, toRemove: List<RemoteVideoSourceMsg?>)
  fun initialAudioSelection(): String?
  fun listAudioDevices(): List<String?>
  fun updateAudioDevice(deviceName: String): Boolean

  companion object {
    /** The codec used by ChimeHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ChimeApiPigeonCodec()
    }
    /** Sets up an instance of `ChimeHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ChimeHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.manageAudioPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.manageAudioPermissions{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ChimeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ChimeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.manageVideoPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.manageVideoPermissions{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ChimeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ChimeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.hasAudioPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hasAudioPermissions())
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.hasVideoPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hasVideoPermissions())
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.joinMeeting$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val joinInfoArg = args[0] as JoinInfoMsg
            val wrapped: List<Any?> = try {
              api.joinMeeting(joinInfoArg)
              listOf(null)
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.stopMeeting$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopMeeting()
              listOf(null)
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.mute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.mute())
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.unmute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.unmute())
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.startLocalVideo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startLocalVideo()
              listOf(null)
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.stopLocalVideo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopLocalVideo()
              listOf(null)
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.startScreenShare$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startScreenShare()
              listOf(null)
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.stopScreenShare$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopScreenShare()
              listOf(null)
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.sendDataMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val topicArg = args[0] as String
            val dataArg = args[1] as String
            val lifetimeMsArg = args[2] as Long
            val wrapped: List<Any?> = try {
              api.sendDataMessage(topicArg, dataArg, lifetimeMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.switchCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.switchCamera()
              listOf(null)
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.activeCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.activeCamera())
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.setLocalVideoMaxBitrate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val maxBitrateKbpsArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setLocalVideoMaxBitrate(maxBitrateKbpsArg)
              listOf(null)
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.updateVideoSourceSubscriptions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val toAddArg = args[0] as List<RemoteVideoSourceMsg?>
            val toRemoveArg = args[1] as List<RemoteVideoSourceMsg?>
            val wrapped: List<Any?> = try {
              api.updateVideoSourceSubscriptions(toAddArg, toRemoveArg)
              listOf(null)
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.initialAudioSelection$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.initialAudioSelection())
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.listAudioDevices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.listAudioDevices())
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_amazon_chime.ChimeHostApi.updateAudioDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceNameArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.updateAudioDevice(deviceNameArg))
            } catch (exception: Throwable) {
              ChimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Defines operations called from Native to Dart.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class ChimeFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ChimeFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      ChimeApiPigeonCodec()
    }
  }
  fun onAttendeeJoined(attendeeArg: AttendeeMsg, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeeJoined$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(attendeeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAttendeeLeft(attendeeArg: AttendeeMsg, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeeLeft$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(attendeeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAttendeeDropped(attendeeArg: AttendeeMsg, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeeDropped$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(attendeeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAttendeeMuted(attendeeArg: AttendeeMsg, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeeMuted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(attendeeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAttendeeUnmuted(attendeeArg: AttendeeMsg, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeeUnmuted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(attendeeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onVideoTileAdded(tileArg: VideoTileMsg, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onVideoTileAdded$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(tileArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onVideoTileRemoved(tileArg: VideoTileMsg, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onVideoTileRemoved$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(tileArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAudioSessionStarted(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAudioSessionStarted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAudioSessionStopped(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAudioSessionStopped$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAudioSessionStartConnecting(reconnectingArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAudioSessionStartConnecting$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(reconnectingArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAudioSessionDropped(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAudioSessionDropped$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAudioSessionCancelledReconnect(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAudioSessionCancelledReconnect$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** [isPoor]: true when connection became poor, false when it recovered. */
  fun onConnectionQualityChanged(isPoorArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onConnectionQualityChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(isPoorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onActiveSpeakersChanged(attendeeIdsArg: List<String?>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onActiveSpeakersChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(attendeeIdsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onVideoTilePaused(tileArg: VideoTileMsg, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onVideoTilePaused$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(tileArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onVideoTileResumed(tileArg: VideoTileMsg, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onVideoTileResumed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(tileArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** [state]: 0=started, 1=stopped */
  fun onContentShareStateChanged(stateArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onContentShareStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAttendeesVolumeChanged(updatesArg: List<AttendeeVolumeMsg>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeesVolumeChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(updatesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAttendeesSignalChanged(updatesArg: List<AttendeeSignalMsg>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onAttendeesSignalChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(updatesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onDataMessageReceived(messageArg: DataMessageMsg, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onDataMessageReceived$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onRemoteVideoSourcesAvailable(sourcesArg: List<RemoteVideoSourceMsg?>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onRemoteVideoSourcesAvailable$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sourcesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onRemoteVideoSourcesUnavailable(sourcesArg: List<RemoteVideoSourceMsg?>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onRemoteVideoSourcesUnavailable$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sourcesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Periodic metrics: map of metric name → numeric value. */
  fun onMeetingMetricsReceived(metricsArg: Map<String?, Any?>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onMeetingMetricsReceived$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(metricsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Structured analytics event from the SDK (e.g. meetingStartSucceeded, meetingFailed). */
  fun onMeetingEventReceived(nameArg: String, attributesArg: Map<String?, Any?>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_amazon_chime.ChimeFlutterApi.onMeetingEventReceived$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(nameArg, attributesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ChimeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
